<a href="https://colab.research.google.com/github/brian3073456/work/blob/master/20200326.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
import numpy as np
ar=np.array([2,4,6,8]);  ar.dtype

dtype('int64')

In [0]:
import numpy as np
ar=np.array([2.,4,6,8]);
ar.dtype

dtype('float64')

In [0]:
import numpy as np
f_ar = np.array([13,-3,8.88])
f_ar

array([13.  , -3.  ,  8.88])

In [0]:
import numpy as np
intf_ar=f_ar.astype(int)
intf_ar

array([13, -3,  8])

In [0]:
ar9 = np.eye(3);
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
ar10=np.diag((2,1,4,6));
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [0]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [0]:
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [0]:
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [0]:
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

In [0]:
np.tile(np.array([[1,2],[6,7]]),3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [0]:
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

In [0]:
np.tile(np.array([[1,2],[6,7]]),3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [0]:
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

In [0]:
x = np.arange(2,10).reshape(2,4)
x

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [0]:
y = np.arange(2,10).reshape(4,2)
y

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [0]:
ar=np.array([np.arange(1,6),np.arange(10,15)]); 
ar

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [0]:
ar=np.array([14,15,16]); ar.shape
ar

array([14, 15, 16])

In [0]:

ar=ar[:, np.newaxis]; ar.shape
ar

array([[14],
       [15],
       [16]])

In [0]:
x = np.arange(2,10)
x

array([2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]); 
ar

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [0]:
ar=2*np.arange(6); 
ar

array([ 0,  2,  4,  6,  8, 10])

In [0]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])